//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testes
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbContas
    {
        public int ContaId { get; set; }
        public string Nome { get; set; }
        public string Agencia { get; set; }
        public string ContaCorrente { get; set; }
        public string Senha { get; set; }
        public string Info { get; set; }
    }
}
