//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testes
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEntradas : tbOperacoes
    {
        public Nullable<int> SaidaId { get; set; }
        public Nullable<int> QtdAssociada { get; set; }
    }
}
