//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testes
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbOperacoesTipos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbOperacoesTipos()
        {
            this.tbOperacoes = new HashSet<tbOperacoes>();
        }
    
        public int TipoId { get; set; }
        public string Tipo { get; set; }
        public bool SinalPositivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbOperacoes> tbOperacoes { get; set; }
    }
}
