//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtivoCorrente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AtivoCorrente()
        {
            this.OperacoesTodas = new HashSet<OperacaoComRunningSum>();
            this.OperacoesDeSaida = new HashSet<OperacaoDeSaida>();
        }
    
        public string Codigo { get; set; }
        public int QtdTotal { get; set; }
        public int ContaId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperacaoComRunningSum> OperacoesTodas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperacaoDeSaida> OperacoesDeSaida { get; set; }
        public virtual Conta Conta { get; set; }
    }
}
