//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    
    public partial class CompraDisponivelParaVenda
    {
        public int OperacaoId { get; set; }
        public System.DateTime Data { get; set; }
        public int QtdAssociada { get; set; }
        public int QtdVendida { get; set; }
        public decimal Valor { get; set; }
    }
}
