//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class InvestimentosEntities : DbContext
    {
        public InvestimentosEntities()
            : base("name=InvestimentosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OperacaoTipo> OperacoesTipos { get; set; }
        public virtual DbSet<Conta> Contas { get; set; }
        public virtual DbSet<AtivoDaConta> AtivosDaConta { get; set; }
        public virtual DbSet<Ativo> Ativos { get; set; }
        public virtual DbSet<Operacao> Operacoes { get; set; }
        public virtual DbSet<Associacao> Associacoes { get; set; }
        public virtual DbSet<CotacaoDiaria> CotacoesDiarias { get; set; }
        public virtual DbSet<ContaFundo> ContasFundos { get; set; }
        public virtual DbSet<ContaMes> ContasMeses { get; set; }
        public virtual DbSet<Fundo> Fundos { get; set; }
        public virtual DbSet<FundoMes> FundosMeses { get; set; }
        public virtual DbSet<Movimento> Movimentos { get; set; }
        public virtual DbSet<LCA> LCAs { get; set; }
        public virtual DbSet<LCAMes> LCAMeses { get; set; }
        public virtual DbSet<LCAMovimento> LCAMovimentos { get; set; }
        public virtual DbSet<SaldoEmConta> SaldosEmConta { get; set; }
    
        public virtual ObjectResult<sp_UltimoSaldo_Result> UltimoSaldo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_UltimoSaldo_Result>("UltimoSaldo");
        }
    
        public virtual int sp_PatrimonioPorMes(Nullable<int> contaID)
        {
            var contaIDParameter = contaID.HasValue ?
                new ObjectParameter("ContaID", contaID) :
                new ObjectParameter("ContaID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_PatrimonioPorMes", contaIDParameter);
        }
    
        public virtual ObjectResult<sp_SituacaoImpostoRenda_Result> sp_SituacaoImpostoRenda(Nullable<int> contaID, Nullable<int> ano)
        {
            var contaIDParameter = contaID.HasValue ?
                new ObjectParameter("ContaID", contaID) :
                new ObjectParameter("ContaID", typeof(int));
    
            var anoParameter = ano.HasValue ?
                new ObjectParameter("Ano", ano) :
                new ObjectParameter("Ano", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SituacaoImpostoRenda_Result>("sp_SituacaoImpostoRenda", contaIDParameter, anoParameter);
        }
    }
}
