//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InvestimentosEntities : DbContext
    {
        public InvestimentosEntities()
            : base("name=InvestimentosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OperacaoTipo> OperacoesTipos { get; set; }
        public virtual DbSet<Conta> Contas { get; set; }
        public virtual DbSet<AtivoDaConta> AtivosDaConta { get; set; }
        public virtual DbSet<Ativo> Ativos { get; set; }
        public virtual DbSet<Operacao> Operacoes { get; set; }
        public virtual DbSet<Associacao> Associacoes { get; set; }
        public virtual DbSet<CotacaoDiaria> CotacoesDiarias { get; set; }
        public virtual DbSet<ContaFundo> ContasFundos { get; set; }
        public virtual DbSet<ContaMes> ContasMeses { get; set; }
        public virtual DbSet<Fundo> Fundos { get; set; }
        public virtual DbSet<FundoMes> FundosMeses { get; set; }
        public virtual DbSet<Movimento> Movimentos { get; set; }
    }
}
