//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaldoEmConta
    {
        public int ContaId { get; set; }
        public string Item { get; set; }
        public decimal Valor { get; set; }
    
        public virtual Conta Conta { get; set; }
    }
}
